### ISSUE TITLE
Stable Docker Image does not work

### ISSUE THREAD

**Issue by lumpenpancho** [TiagoCortinhal/cita-checker#1]
Docker Hub image with latest tag has a manifest issue:
` (HTTP code 404) unexpected - no matching manifest for linux/amd64 in the manifest list entries: no match for platform in manifest: not found`

**Comment by TiagoCortinhal** [comment]
Hey @lumpenpancho,

Could you give me more details of how you encounter the error? 

Thanks!

**Comment by lumpenpancho** [comment]
Hi Tiago,

a simple docker pull on windows with docker desktop prompted the error.

Same happened when I tried it on a linux machine. I gave up troubleshooting
when I realized that the bakayarou23/cita-checker:version40 worked without
issues.

Nevertheless, curious to learn about the latest improvements you made.

**Comment by TiagoCortinhal** [comment]
Hey again, 

Strange. I tried with macOS and Linux and it worked. I am glad you found a workaround!


Version 4.0 and latest should be the same (I think I did not change a lot of stuff between both just "cosmetic stuff").  You should have the same python script and vnc capabilities. 


Let me know if anything!

**Comment by lumpenpancho** [comment]
Now it's working! Thx @TiagoCortinhal
